version: "2.2.1"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    environment:
      SEQ_DB: prova-adonis
      SEQ_USER: postgres
      SEQ_PW: Felipe50
      PORT: 3333
      DATABASE_URL: postgres://postgres:Felipe50@localhost:5432/prova-adonis
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Felipe50


